.gitlab-ci.yml

worker-deployment.yaml file does not exist any more.

[pipeline] Adjust sync job after sre-tools repo changes

---

ui/index.html

To fix "Blocked loading mixed active content" in Firefox (and possibly
other browsers).

[ui] Upgrade jquery link to https

---

.gitlab-ci.yml

related to https://github.com/mendersoftware/sre-tools/pull/102

rename in qastatus related repo

---

.gitlab-ci.yml
development.yml

this _should_ fix CI on master 🤞

fix: aligned leftover references to previous backend folder structure

---

docker-compose.yml

... still lacks api gateway routing

feat: added graphql api to ease exploring db data

---

ui/pages/build-status.js

Ticket: QA-155
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>

feat: added repo coverage + coverage aggregates to build status page

---

ui/pages/build-status.js

fix: fixed erroneous coverage rendering + absence of staging info

---

ui/pages/build-status.js

Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

fix embarassing colour error in the nightly status button

---

ui/package-lock.json
ui/package.json
ui/pages/nightlies.js

I was overly trigger happy with the previous PR, this should have been in there too

fix: fixed nightlies component naming & appearance

---

ui/components/navbar.js
ui/pages/index.js

Ticket: None
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>

fix: fixed an issue that prevented external links to a page from working

---

ui/pages/build-status.js

chore(build-status): Add generate-delta-worker build status
Ticket: MEN-5800
Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>

chore(build-status): Add generate-delta-worker build status

---

ui/pages/stats.js

Ticket: None
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

fix: remove extraneous ;

---

ui/src/statistics/spurious-failures-view.js

Ticket: None
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

feat: Add a loader to the test statistics

---

scripts/get-nightly-gitlab.py

Ticket: None
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

fix: it is now the mender-test-bot which triggers the nightlies

---

ui/pages/build-status.js

Ticket: MEN-6086
Signed-off-by: Alex Miliukov <oleksandr.miliukov@northern.tech>

chore: add app-update-module repo to build status

---

ui/pages/nightlies.js

Ticket: None
Signed-off-by: Manuel Zedel <manuel.zedel@northern.tech>

fix: fixed nightlies getting order reversed on repeat route visits

---

ui/pages/build-status.js

Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

Add mender-flash to build status page.

---

ui/pages/nightlies.js

The only way to distinguish which "scheduled" pipelines are triggered from which configured schedule, is to use the dedicated API endpoint `GET /projects/:id/pipeline_schedules/:pipeline_schedule_id/pipelines`.
ref: https://docs.gitlab.com/ee/api/pipeline_schedules.html#get-all-pipelines-triggered-by-a-pipeline-schedule
Unfortunately, this endpoint does not seem to be implemented in GraphQL API, nor there is a way to connect from project -> pipelineSchedules -> pipelines, so we have to fallback to the REST API.
On top of it, this endpoint does not support keyset-based pagination, so the code does a fair amount of API calls.
Originally we assumed that we could just keep the GraphQL query and then filter based on each pipeline variables, but it turns out that the variables endpoint only …

QA-539: chore: Rework code to get nightlies to discriminate between schedules

---

ui/package.json
ui/pages/security-status.js

fix: removed unused attributes to allow building security status page

---

ui/pages/build-status.js

feat: made build status links target proper branch right away

---

ui/pages/nightlies.js

After moving out integration and backend integration tests from `mender-qa` repository, this pipeline represents rather the client side of things.

chore: Modify title to better reflect what the build is

---

ui/package-lock.json
ui/package.json
ui/pages/build-status.js
ui/pages/nightlies.js
ui/src/constants.js
ui/src/nightlies/CalendarView.js
ui/src/nightlies/Dot.js
ui/src/nightlies/Legend.js
ui/src/nightlies/ListView.js

Ticket: QA-789
Changelog: Nonegit@github.com:mineralsfree/mantra.git

feat(gui): added calendar view and integration pipeline to nightlies

---

ui/src/constants.js
ui/src/nightlies/Dot.js

fix: rely on regular link functionality to open nightlies

---

ui/src/nightlies/CalendarView.js
ui/src/nightlies/Dot.js

QA-1000 - show hidden calendar entries

---

ui/pages/nightlies.js

chore: Add nightlies for mender-gateway master and 2.0x

---

.gitlab-ci.yml
docker-compose.yml

ci: replace bitnami image
